### ISSUE TITLE
localtuya shows Config flow could not be loaded after update to HA 2025.12

### ISSUE THREAD

**Issue by ceeram** [rospogrigio/localtuya-homeassistant#2124]
The localtuya integration is broken after HA update from 2025.11.3 to 2025.12. I had added some lamps already, if i now try to add more after the update of HA i get `Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

**Comment by Nelferjani** [comment]
same issue after last Update... was working fine a few days ago ..

**Comment by sp2lsd** [comment]
Just done update to HA 2025.12 and results exactly as colegues above. Any patch or solutions?

**Comment by captnalex** [comment]
Same here

**Comment by hazem3dmax** [comment]
Same to me

**Comment by mspiridakis** [comment]
Same here

**Comment by ronald0krueger** [comment]
Same here

**Comment by zzaal** [comment]
Same here too (;

**Comment by chwdt** [comment]
Same here too.

**Comment by AFLAPPIE** [comment]
Same here

**Comment by lucalio95** [comment]
Same here

**Comment by ceeram** [comment]
Good to hear it's not just me. i am a new HA user, only few days in. Meanwhile, it looks like localtuya is not actively maintained anymore. I have tried tuya-local and works fine for me, as it might take a while for this issue to be solved, unless someone steps up from the community.

**Comment by MBj1703** [comment]
Looks like I have the same: https://github.com/rospogrigio/localtuya/issues/2126

**Comment by nirvatus** [comment]
python
# En /config/custom_components/localtuya/config_flow.py, línea 396:
# Cambia de:
self.config_entry = config_entry

# A:
self._config_entry = config_entry

**Comment by MBj1703** [comment]
Thank you, issue fixed!

**Comment by lucalio95** [comment]
fixed!

**Comment by Nelferjani** [comment]
fixed.. thank you @nirvatus  !

**Comment by UB1957** [comment]
fixed... Thanks a lot @nirvatus !!!

**Comment by ronald0krueger** [comment]
fixed! Thank you @nirvatus !

**Comment by Meskalimneo** [comment]
How to fix this? Where to fix this in HA?

> Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble

**Comment by ArieSneek** [comment]
Thanks @nirvatus 👍

**Comment by ArieSneek** [comment]
> How to fix this? Where to fix this in HA?
> 
> > Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble

Go to /config/custom_components/localtuya/config_flow.py
And than change line 396 to "self._config_entry = config_entry"
This is because 2025.12 made config_entry read only , but Local Tuya expects it to be a private variable. The _ makes it that you bypass this.

**Comment by Meskalimneo** [comment]
> > How to fix this? Where to fix this in HA?
> > > Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble
> 
> Go to /config/custom_components/localtuya/config_flow.py And than change line 396 to "self._config_entry = config_entry" This is because 2025.12 made config_entry read only , but Local Tuya expects it to be a private variable. The _ makes it that you bypass this.

fixed! Thank you @ArieSneek

**Comment by F1Racer68** [comment]
@nirvatus solution worked for me as well. Thanks!

**Comment by cmgenius** [comment]
> > > How to fix this? Where to fix this in HA?
> > > > Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble
> > 
> > 
> > Go to /config/custom_components/localtuya/config_flow.py And than change line 396 to "self._config_entry = config_entry" This is because 2025.12 made config_entry read only , but Local Tuya expects it to be a private variable. The _ makes it that you bypass this.
> 
Thanks, I made the change using the File Editor addon and then had to restart HA and its working! Thank you!

**Comment by chintan124** [comment]
> > How to fix this? Where to fix this in HA?
> > > Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble
> 
> Go to /config/custom_components/localtuya/config_flow.py And than change line 396 to "self._config_entry = config_entry" This is because 2025.12 made config_entry read only , but Local Tuya expects it to be a private variable. The _ makes it that you bypass this.

Thank you!!! The issue is fixed!

**Comment by rrooggiieerr** [comment]
This issue is related to a change in the options flow architecture from 1 year ago!

https://developers.home-assistant.io/blog/2024/11/12/options-flow/

the `self._config_entry = config_entry` may make it work, but whoever came up with that doesn't understand what the issue is about. `self.config_entry` is now part of the config flow by default and doesn't need to be assigned at all. Just delete the whole  `self.config_entry = config_entry` all together.

@chwdt has created a fix https://github.com/rospogrigio/localtuya/pull/2127 that does it the right way, but the real problem is that architectural changes of a year ago are not implemented.

This also happened when HA 2025.5 was releases. An architectural change form a year earlier broke @rospogrigio version of LocalTuya, so it's not a one time thing but over all poor maintenance.

Just start using xZetsubou version of LocalTuya https://github.com/xZetsubou/hass-localtuya/ because that one is properly maintained (and has a lot more features)

**Comment by ceeram** [comment]
thanks @rrooggiieerr suggesting to replace localtuya in HACS with the more actively maintained version seems the best way for all users of localtuya and keep this integration alive and kicking

**Comment by grischa81** [comment]
@rrooggiieerr Vielen Dank für die Info! Funktioniert viel besser als localtuya!

**Comment by Bildass** [comment]
Hi everyone,

  I've been facing the same issues with Home Assistant 2025.x compatibility.
  Since the original LocalTuya hasn't been updated for a while, I created an
  actively maintained fork called **LocalTuya 2.0** that addresses these problems.

  **Key fixes & features:**
  - ✅ Full HA 2025.x compatibility (tested with 2025.12)
  - ✅ Quick Edit - change IP/local_key without reconfiguring all entities
  - ✅ Cloud Sync - fetch all local_keys with one click
  - ✅ Runs alongside original LocalTuya (different domain)

 Repository: https://github.com/Bildass/localtuya

  It's a drop-in alternative you can test without removing the original.
  Happy to help if you have questions!

**Comment by rrooggiieerr** [comment]
@Bildass, what makes your LocalTuya better than @xZetsubou version?

**Comment by philip-dt** [comment]
> [@Bildass](https://github.com/Bildass), what makes your LocalTuya better than [@xZetsubou](https://github.com/xZetsubou) version?

"🔄 Parallel Installation
Run alongside original LocalTuya:

Different domain (localtuya_bildass)
Test before migrating
No conflicts"

This is a pretty nice benefit, especially for novice users.

**Comment by kalatos86** [comment]
> python
> # En /config/custom_components/localtuya/config_flow.py, línea 396:
> # Cambia de:
> 
> self.config_entry = config_entry
> # A:
> 
> self._config_entry = config_entry

Works also for me, thanks so much! I was fighting with that one since two last evenings :)

**Comment by bkqc** [comment]
> > [@Bildass](https://github.com/Bildass), what makes your LocalTuya better than [@xZetsubou](https://github.com/xZetsubou) version?
> 
> "🔄 Parallel Installation Run alongside original LocalTuya:
> 
> Different domain (localtuya_bildass) Test before migrating No conflicts"
> 
> This is a pretty nice benefit, especially for novice users.

Have you tried [this](https://github.com/xZetsubou/hass-localtuya/discussions/79)? I know this is not a side by side setup but if the inplace "upgrade" works fine, what is the problem?

**Comment by bowenda** [comment]
I have the same issue. Just implemented the suggested fix in HA 2025.12 but no go. Local Tuya Version 5.2.3, Core 2025.12.3, Front end 20251203.2, OS V16.3. i.e. everything is upto date. My local devices still function but cannot and new ones. The Tuya Cloud app works fine.

**Comment by rrooggiieerr** [comment]
@philip-dt the guy is not even 1 month GitHub member, changes to the code are minimal while @xZetsubou has been working almost 2 years on improving the code and adding features. It's a drop in replacement, that's better than a different domain next to a not working domain

**Comment by bowenda** [comment]
I also have this issue but cannot get the trial account extended at Tuya without paying. "Failed to retrieve device list. Error 28841002: No permissions. Your subscription to cloud development plan has expired."

UPDATE: I finally managed to extend my cloud development plan but still get internal sever error. Even tried adding a new instance link to the cloud and same issue. In fact that crashed LocalTuya completely and I needed to restore a backup! At my the end of my patience now :-(

**Comment by grf21a** [comment]
Thanks @kalatos86 & @nirvatus.  I replaced that line of code in the "config_flow.py" file, then rebooted HA and my issue was resolved.

**Comment by HomeKM** [comment]
Vielen Dank "nirvatus", funktioniert wieder.

**Comment by bowenda** [comment]
I replaced all of the self.config with self_.config, 16 entries if config_flow.py. My error 500 has disappeared and now when adding a device, it shows current and new devices to add (not sure why the currently configured are listed). However, I cannot add the devices as I now get a 113 error as shown in the log entry below...

"This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
integration: LocalTuya (documentation, issues)
First occurred: 2:52:30 PM (2 occurrences)
Last logged: 3:06:49 PM

Unexpected exception: [Errno 113] Connect call failed ('192.168.68.61', 6668)
Traceback (most recent call last):
File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
self.dps_strings = await validate_input(self.hass, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
interface = await pytuya.connect(
^^^^^^^^^^^^^^^^^^^^^
...<5 lines>...
)
^
File "/config/custom_components/localtuya/pytuya/init.py", line 1182, in connect
_, protocol = await loop.create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...<10 lines>...
)
^
File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1171, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1146, in create_connection
sock = await self._connect_sock(
^^^^^^^^^^^^^^^^^^^^^^^^^
exceptions, addrinfo, laddr_infos)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1045, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 641, in sock_connect
return await fut
^^^^^^^^^
File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 681, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.68.61', 6668)"

**Comment by benblasco** [comment]
@bowenda 

> I replaced all of the self.config with self_.config, 16 entries if config_flow.py. 

The instructions said just to replace it once, on line 396. Did you try reverting all the other changes and just using the change in line 396?

**Comment by KotBayun69** [comment]
> python
> 
> # En /config/custom_components/localtuya/config_flow.py, línea 396:
> # Cambia de:
> self.config_entry = config_entry
> 
> # A:
> self._config_entry = config_entry

Worked for me too. Thank You very much.

**Comment by KotBayun69** [comment]
@nirvatus 
I took a liberty to translate your solution:

In `/config/custom_components/localtuya/config_flow.py` replace the line `396`
```
self.config_entry = config_entry
```
with 
```
self._config_entry = config_entry
```

**Comment by rrooggiieerr** [comment]
I say this again, you don't need to replace the `self.config_entry = config_entry` line, just delete it.

Better yet, replace the integration with this maintained version: https://github.com/xZetsubou/hass-localtuya/

https://github.com/rospogrigio/localtuya/issues/2124#issuecomment-3617389161

**Comment by yakupzz** [comment]
only change the line 396 and work!

**Comment by jrabkid** [comment]
> python
> 
> # En /config/custom_components/localtuya/config_flow.py, línea 396:
> # Cambia de:
> self.config_entry = config_entry
> 
> # A:
> self._config_entry = config_entry

You sir are a legend and a scholar

**Comment by BitEater21** [comment]
Any idea regarding a new release?

**Comment by jrabkid** [comment]
> Any idea regarding a new release?

The update can thankfully wait as the fix is above for now, 2 seconds fixes it.

**Comment by theBlbDan** [comment]
> > Any idea regarding a new release?
> 
> The update can thankfully wait as the fix is above for now, 2 seconds fixes it.

Mine took me 2 minutes as it was on line 243 for me.

**Comment by jrabkid** [comment]
> > > Any idea regarding a new release?
> > 
> > 
> > The update can thankfully wait as the fix is above for now, 2 seconds fixes it.
> 
> Mine took me 2 minutes as it was on line 243 for me.

I used search to find the line as I know they can vary occasionally. But yes it is a slight inconvenience but then that's home assistant for you I guess. I'd say the devs will update but it's like cat and mouse when HA do their updates the Devs have to play catch-up, especially for apps on HACS.

**Comment by ericdpeterson** [comment]
> > > > Any idea regarding a new release?
> > > 
> > > 
> > > The update can thankfully wait as the fix is above for now, 2 seconds fixes it.
> > 
> > 
> > Mine took me 2 minutes as it was on line 243 for me.
> 
> I used search to find the line as I know they can vary occasionally. But yes it is a slight inconvenience but then that's home assistant for you I guess. I'd say the devs will update but it's like cat and mouse when HA do their updates the Devs have to play catch-up, especially for apps on HACS.

The edit does only take seconds, but it didn't appear to fix the issue for me. May I ask which version of HA you're running where it worked?  I'm running 2026.1.3.

<img width="1077" height="477" alt="Image" src="https://github.com/user-attachments/assets/313653e4-5fab-41a0-a055-6b24c2730c6c" />

**Comment by jrabkid** [comment]
Yea same version of HA here and works perfect. I'm not at home currently to compare your details to mine although I see you have commented you lines out, are they supposed to me? I can't remember if they are or not on mine.

**Comment by ericdpeterson** [comment]
Good to know, thanks. 
No I didn't comment those out, they remain untouched. I appreciate you're willingness to compare, thank you. In the meantime, I'll keep hunting around. 

UPDATE (27-JAN-2026):  I did finally get it to work. When the HA debug logs didn't reveal any issues, I restarted HA multiple times. Best I can figure is that when new items are added to the Tuya Developer Platform, it takes much longer than I expected for those items to appear as "controllable" - and flush through. 

<img width="1861" height="501" alt="Image" src="https://github.com/user-attachments/assets/d0cf7d6e-0eca-4138-892c-00807261cd9d" />

**Comment by dedmen** [comment]
Note this was fixed by https://github.com/rospogrigio/localtuya/commit/59c95cd06c2696afc98f6bc52d5fa060f3c517da and it was released in version 5.2.5
Its unclear why this ticket is still open?

**Comment by ehran** [comment]
as of today still not working for me even after removing the line in question :(
